<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-L545F58" name="tests.IdfcBank" tests="4" failures="0" timestamp="2021-02-07T19:59:48 IST" time="2.783" errors="1">
  <testcase name="setUp" time="2.783" classname="tests.IdfcBank">
    <error type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find &#039;adb.exe&#039; in [&quot;C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\platform-tools\\adb.exe&quot;,&quot;C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\emulator\\adb.exe&quot;,&quot;C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\adb.exe&quot;,&quot;C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\bin\\adb.exe&quot;]. Do you have Android Build Tools installed at &#039;C:\Users\ACER\Desktop\android-sdk\cmdline-tools&#039;?
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-L545F58&#039;, ip: &#039;192.168.0.148&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_261&#039;
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find &#039;adb.exe&#039; in [&quot;C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\platform-tools\\adb.exe&quot;,&quot;C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\emulator\\adb.exe&quot;,&quot;C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\adb.exe&quot;,&quot;C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\bin\\adb.exe&quot;]. Do you have Android Build Tools installed at &#039;C:\Users\ACER\Desktop\android-sdk\cmdline-tools&#039;?
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-L545F58&#039;, ip: &#039;192.168.0.148&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_261&#039;
Driver info: driver.version: AppiumDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in ["C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\platform-tools\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\emulator\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\bin\\adb.exe"]. Do you have Android Build Tools installed at 'C:\Users\ACER\Desktop\android-sdk\cmdline-tools'?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-L545F58', ip: '192.168.0.148', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in ["C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\platform-tools\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\emulator\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\bin\\adb.exe"]. Do you have Android Build Tools installed at 'C:\Users\ACER\Desktop\android-sdk\cmdline-tools'?
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-L545F58', ip: '192.168.0.148', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:247)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:338)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)
at tests.IdfcBank.setUp(IdfcBank.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:193)
... 36 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in ["C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\platform-tools\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\emulator\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\bin\\adb.exe"]. Do you have Android Build Tools installed at 'C:\Users\ACER\Desktop\android-sdk\cmdline-tools'?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-L545F58', ip: '192.168.0.148', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in ["C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\platform-tools\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\emulator\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\adb.exe","C:\\Users\\ACER\\Desktop\\android-sdk\\cmdline-tools\\tools\\bin\\adb.exe"]. Do you have Android Build Tools installed at 'C:\Users\ACER\Desktop\android-sdk\cmdline-tools'?
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:388:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
... 41 more
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase name="login" time="0.000" classname="tests.IdfcBank">
    <skipped/>
  </testcase> <!-- login -->
  <system-out/>
  <testcase name="getBalance" time="0.000" classname="tests.IdfcBank">
    <skipped/>
  </testcase> <!-- getBalance -->
  <system-out/>
  <testcase name="myProfile" time="0.000" classname="tests.IdfcBank">
    <skipped/>
  </testcase> <!-- myProfile -->
  <system-out/>
</testsuite> <!-- tests.IdfcBank -->
